"""empty message

Revision ID: 39389b5ea7a6
Revises: 44c91a7f5dba
Create Date: 2019-07-12 17:59:21.249947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39389b5ea7a6'
down_revision = '44c91a7f5dba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('episode', sa.Column('audio_time', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('episode', 'audio_time')
    # ### end Alembic commands ###
